/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `movies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `imdbID` longtext DEFAULT NULL,
  `Title` longtext DEFAULT NULL,
  `Year` text DEFAULT NULL,
  `imdbRating` text DEFAULT NULL,
  `Genre` text DEFAULT NULL,
  `Plot` longtext DEFAULT NULL,
  `Actors` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `imdbLink` longtext DEFAULT NULL,
  `Poster` longtext DEFAULT NULL,
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `imdbID` (`imdbID`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=236 DEFAULT CHARSET=utf8;

DELETE FROM `movies`;
/*!40000 ALTER TABLE `movies` DISABLE KEYS */;
INSERT INTO `movies` (`id`, `imdbID`, `Title`, `Year`, `imdbRating`, `Genre`, `Plot`, `Actors`, `imdbLink`, `Poster`) VALUES
	(177, 'tt0944947', 'Game of Thrones', '2011–2019', '9.2', 'Action, Adventure, Drama', 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.', 'Emilia Clarke, Peter Dinklage, Kit Harington', 'https://www.imdb.com/title/tt0944947', 'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg'),
	(178, 'tt1515091', 'Sherlock Holmes: A Game of Shadows', '2011', '7.5', 'Action, Adventure, Mystery', 'Detective Sherlock Holmes is on the trail of criminal mastermind Professor Moriarty, who is carrying out a string of random crimes across Europe.', 'Robert Downey Jr., Jude Law, Jared Harris', 'https://www.imdb.com/title/tt1515091', 'https://m.media-amazon.com/images/M/MV5BMTQwMzQ5Njk1MF5BMl5BanBnXkFtZTcwNjIxNzIxNw@@._V1_SX300.jpg'),
	(179, 'tt0126916', 'For Love of the Game', '1999', '6.6', 'Drama, Romance, Sport', 'After 19 years of playing the game he\'s loved his whole life, Detroit Tigers pitcher Billy Chapel has to decide if he\'s going to risk everything and put everything out there.', 'Kevin Costner, Kelly Preston, John C. Reilly', 'https://www.imdb.com/title/tt0126916', 'https://m.media-amazon.com/images/M/MV5BZDgzY2NkMTgtODQwZC00MWEzLWFlZjQtZTcxOTc3NzU1MDVhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg'),
	(180, 'tt0077594', 'Game of Death', '1978', '6.1', 'Action, Crime, Drama', 'A martial arts movie star must fake his death to find the people who are trying to kill him.', 'Bruce Lee, Gig Young, Dean Jagger', 'https://www.imdb.com/title/tt0077594', 'https://m.media-amazon.com/images/M/MV5BNDY2N2EyOTAtMGY4Zi00Mjc3LTkzNTYtNjM2YjNhYjM2MWM5XkEyXkFqcGdeQXVyMTQ2ODE0NDA@._V1_SX300.jpg'),
	(181, 'tt1446072', 'Game of Death', '2011', '4.7', 'Action, Adventure, Thriller', 'Secret Ops agent Marcus is sent to Detroit to take out an arms dealer and the head of the hedge fund that is financing him. His CIA backup has other plans and turns on him and it\'s a fight to survive in a hospital.', 'Wesley Snipes, Aunjanue Ellis, Zoë Bell', 'https://www.imdb.com/title/tt1446072', 'https://m.media-amazon.com/images/M/MV5BNWRkMDhiOWItZWE5ZC00OTQ1LTk1ZTItMTkyMmRhNTAzMzE5XkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_SX300.jpg'),
	(182, 'tt10090796', 'Game of Thrones: The Last Watch', '2019', '7.2', 'Documentary', 'Chronicling the creation of Game of Thrones (2011)\'s final season, its most ambitious and complicated one.', 'Kevin Alexander, Alfie Allen, Jacob Anderson, Gethin Anthony', 'https://www.imdb.com/title/tt10090796', 'https://m.media-amazon.com/images/M/MV5BZDdlMzQzNDQtNTAxMS00NTMyLTgxYTAtYzQ0OGI1YzZhY2Y3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg'),
	(183, 'tt3391176', 'Game of Thrones: A Telltale Games Series', '2014', '8.3', 'Adventure, Fantasy, War', 'During the War of the Five Kings, House Forrester find themselves embroiled in a web of deceit and corruption.', 'Lena Headey, Natalie Dormer, Peter Dinklage, Iwan Rheon', 'https://www.imdb.com/title/tt3391176', 'https://m.media-amazon.com/images/M/MV5BODg0YTM4NzEtZDQyNi00M2MzLWE3MDQtNjcxNTkxNWM0NzNhXkEyXkFqcGdeQXVyMjM5NzU3OTM@._V1_SX300.jpg'),
	(184, 'tt0354595', 'The Game of Their Lives', '2005', '6.1', 'Drama, History, Sport', 'Based on a true story, this film tells the tale of the 1950 U.S. soccer team, who, against all odds, beat England 1 - 0 in the city of Belo Horizonte, Brazil. Although no U.S. team has ever won a World Cup title, this story is about ', 'Wes Bentley, Gerard Butler, Gavin Rossdale', 'https://www.imdb.com/title/tt0354595', 'https://m.media-amazon.com/images/M/MV5BMjE1NTg3MDkxN15BMl5BanBnXkFtZTcwNTg4ODgyMQ@@._V1_SX300.jpg'),
	(185, 'tt4074374', 'Game of Silence', '2016', '7.1', 'Drama', 'A rising attorney finds his perfectly crafted life threatened when his long-lost childhood friends threaten to expose a dark secret from their past.', 'David Lyons, Michael Raymond-James, Larenz Tate', 'https://www.imdb.com/title/tt4074374', 'https://m.media-amazon.com/images/M/MV5BMTUzMjE0OTIxMl5BMl5BanBnXkFtZTgwOTExMDQzODE@._V1_SX300.jpg'),
	(186, 'tt0489105', 'King Kong: The Official Game of the Movie', '2005', '7.4', 'Action, Adventure, Fantasy', 'Based on the events of the motion picture King Kong (2005), this game allows the player to play as man, or as Kong. When the crew arrive at Skull Island, they are faced with many thrills and challenges throughout.', 'Jamie Bell, Jack Black, Adrien Brody, Thomas Kretschmann', 'https://www.imdb.com/title/tt0489105', 'https://m.media-amazon.com/images/M/MV5BNjE0NDEwMTQ3Ml5BMl5BanBnXkFtZTcwMDg0MDkzMQ@@._V1_SX300.jpg'),
	(187, 'tt0892769', 'How to Train Your Dragon', '2010', '8.1', 'Animation, Action, Adventure', 'A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.', 'Jay Baruchel, Gerard Butler, Christopher Mintz-Plasse', 'https://www.imdb.com/title/tt0892769', 'https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg'),
	(188, 'tt1568346', 'The Girl with the Dragon Tattoo', '2011', '7.8', 'Crime, Drama, Mystery', 'Journalist Mikael Blomkvist is aided in his search for a woman who has been missing for forty years by Lisbeth Salander, a young computer hacker.', 'Daniel Craig, Rooney Mara, Christopher Plummer', 'https://www.imdb.com/title/tt1568346', 'https://m.media-amazon.com/images/M/MV5BMTczNDk4NTQ0OV5BMl5BanBnXkFtZTcwNDAxMDgxNw@@._V1_SX300.jpg'),
	(189, 'tt1646971', 'How to Train Your Dragon 2', '2014', '7.8', 'Animation, Action, Adventure', 'When Hiccup and Toothless discover an ice cave that is home to hundreds of new wild dragons and the mysterious Dragon Rider, the two friends find themselves at the center of a battle to protect the peace.', 'Jay Baruchel, Cate Blanchett, Gerard Butler', 'https://www.imdb.com/title/tt1646971', 'https://m.media-amazon.com/images/M/MV5BMzMwMTAwODczN15BMl5BanBnXkFtZTgwMDk2NDA4MTE@._V1_SX300.jpg'),
	(190, 'tt0289765', 'Red Dragon', '2002', '7.2', 'Crime, Drama, Thriller', 'A retired FBI agent with psychological gifts is assigned to help track down "The Tooth Fairy", a mysterious serial killer. Aiding him is imprisoned forensic psychiatrist Dr. Hannibal "The Cannibal" Lecter.', 'Anthony Hopkins, Edward Norton, Ralph Fiennes', 'https://www.imdb.com/title/tt0289765', 'https://m.media-amazon.com/images/M/MV5BMTQ4MDgzNjM5MF5BMl5BanBnXkFtZTYwMjUwMzY2._V1_SX300.jpg'),
	(191, 'tt0859163', 'The Mummy: Tomb of the Dragon Emperor', '2008', '5.2', 'Action, Fantasy, Horror', 'In the Far East, Alex O\'Connell, the son of famed mummy fighters Rick and Evy O\'Connell, unearths the mummy of the first Emperor of Qin -- a shape-shifting entity cursed by a witch centuries ago.', 'Brendan Fraser, Jet Li, Maria Bello', 'https://www.imdb.com/title/tt0859163', 'https://m.media-amazon.com/images/M/MV5BMTU4NDIzMDY1OV5BMl5BanBnXkFtZTcwNjQxMzk3MQ@@._V1_SX300.jpg'),
	(192, 'tt0214341', 'Dragon Ball Z', '1996–2003', '8.7', 'Animation, Action, Adventure', 'After learning that he is from another planet, a warrior named Goku and his friends are prompted to defend it from an onslaught of extraterrestrial enemies.', 'Doc Harris, Christopher Sabat, Scott McNeil', 'https://www.imdb.com/title/tt0214341', 'https://m.media-amazon.com/images/M/MV5BNGM5MTEyZDItZWNhOS00NzNkLTgwZTAtNWIzY2IzZmExOWMxXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg'),
	(193, 'tt2386490', 'How to Train Your Dragon: The Hidden World', '2019', '7.5', 'Animation, Action, Adventure', 'When Hiccup discovers Toothless isn\'t the only Night Fury, he must seek "The Hidden World", a secret Dragon Utopia before a hired tyrant named Grimmel finds it first.', 'Jay Baruchel, America Ferrera, F. Murray Abraham', 'https://www.imdb.com/title/tt2386490', 'https://m.media-amazon.com/images/M/MV5BMjIwMDIwNjAyOF5BMl5BanBnXkFtZTgwNDE1MDc2NTM@._V1_SX300.jpg'),
	(194, 'tt5109280', 'Raya and the Last Dragon', '2021', '7.4', 'Animation, Action, Adventure', 'In a realm known as Kumandra, a re-imagined Earth inhabited by an ancient civilization, a warrior named Raya is determined to find the last dragon.', 'Kelly Marie Tran, Awkwafina, Gemma Chan', 'https://www.imdb.com/title/tt5109280', 'https://m.media-amazon.com/images/M/MV5BZWNiOTc4NGItNGY4YS00ZGNkLThkOWEtMDE2ODcxODEwNjkwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg'),
	(195, 'tt1201607', 'Harry Potter and the Deathly Hallows: Part 2', '2011', '8.1', 'Adventure, Drama, Fantasy', 'Harry, Ron, and Hermione search for Voldemort\'s remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 'https://www.imdb.com/title/tt1201607', 'https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg'),
	(196, 'tt0241527', 'Harry Potter and the Sorcerer\'s Stone', '2001', '7.6', 'Adventure, Family, Fantasy', 'An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.', 'Daniel Radcliffe, Rupert Grint, Richard Harris', 'https://www.imdb.com/title/tt0241527', 'https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg'),
	(197, 'tt0295297', 'Harry Potter and the Chamber of Secrets', '2002', '7.4', 'Adventure, Family, Fantasy', 'An ancient prophecy seems to be coming true when a mysterious presence begins stalking the corridors of a school of magic and leaving its victims paralyzed.', 'Daniel Radcliffe, Rupert Grint, Emma Watson', 'https://www.imdb.com/title/tt0295297', 'https://m.media-amazon.com/images/M/MV5BMTcxODgwMDkxNV5BMl5BanBnXkFtZTYwMDk2MDg3._V1_SX300.jpg'),
	(198, 'tt0304141', 'Harry Potter and the Prisoner of Azkaban', '2004', '7.9', 'Adventure, Family, Fantasy', 'Harry Potter, Ron and Hermione return to Hogwarts School of Witchcraft and Wizardry for their third year of study, where they delve into the mystery surrounding an escaped prisoner who poses a dangerous threat to the young wizard.', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 'https://www.imdb.com/title/tt0304141', 'https://m.media-amazon.com/images/M/MV5BMTY4NTIwODg0N15BMl5BanBnXkFtZTcwOTc0MjEzMw@@._V1_SX300.jpg'),
	(199, 'tt0330373', 'Harry Potter and the Goblet of Fire', '2005', '7.7', 'Adventure, Family, Fantasy', 'Harry Potter finds himself competing in a hazardous tournament between rival schools of magic, but he is distracted by recurring nightmares.', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 'https://www.imdb.com/title/tt0330373', 'https://m.media-amazon.com/images/M/MV5BMTI1NDMyMjExOF5BMl5BanBnXkFtZTcwOTc4MjQzMQ@@._V1_SX300.jpg'),
	(200, 'tt0373889', 'Harry Potter and the Order of the Phoenix', '2007', '7.5', 'Action, Adventure, Family', 'With their warning about Lord Voldemort\'s return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts.', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 'https://www.imdb.com/title/tt0373889', 'https://m.media-amazon.com/images/M/MV5BMTM0NTczMTUzOV5BMl5BanBnXkFtZTYwMzIxNTg3._V1_SX300.jpg'),
	(201, 'tt0926084', 'Harry Potter and the Deathly Hallows: Part 1', '2010', '7.7', 'Adventure, Fantasy, Mystery', 'As Harry, Ron, and Hermione race against time and evil to destroy the Horcruxes, they uncover the existence of the three most powerful objects in the wizarding world: the Deathly Hallows.', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 'https://www.imdb.com/title/tt0926084', 'https://m.media-amazon.com/images/M/MV5BMTQ2OTE1Mjk0N15BMl5BanBnXkFtZTcwODE3MDAwNA@@._V1_SX300.jpg'),
	(202, 'tt0417741', 'Harry Potter and the Half-Blood Prince', '2009', '7.6', 'Action, Adventure, Family', 'As Harry Potter begins his sixth year at Hogwarts, he discovers an old book marked as "the property of the Half-Blood Prince" and begins to learn more about Lord Voldemort\'s dark past.', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 'https://www.imdb.com/title/tt0417741', 'https://m.media-amazon.com/images/M/MV5BNzU3NDg4NTAyNV5BMl5BanBnXkFtZTcwOTg2ODg1Mg@@._V1_SX300.jpg'),
	(203, 'tt0098635', 'When Harry Met Sally...', '1989', '7.6', 'Comedy, Drama, Romance', 'Harry and Sally have known each other for years, and are very good friends, but they fear sex would ruin the friendship.', 'Billy Crystal, Meg Ryan, Carrie Fisher', 'https://www.imdb.com/title/tt0098635', 'https://m.media-amazon.com/images/M/MV5BMjE0ODEwNjM2NF5BMl5BanBnXkFtZTcwMjU2Mzg3NA@@._V1_SX300.jpg'),
	(204, 'tt0066999', 'Dirty Harry', '1971', '7.7', 'Action, Crime, Thriller', 'When a madman calling himself "the Scorpio Killer" menaces the city, tough-as-nails San Francisco Police Inspector "Dirty" Harry Callahan is assigned to track down and ferret out the crazed psychopath.', 'Clint Eastwood, Andrew Robinson, Harry Guardino', 'https://www.imdb.com/title/tt0066999', 'https://m.media-amazon.com/images/M/MV5BMzdhMTM2YTItOWU2YS00MTM0LTgyNDYtMDM1OWM3NzkzNTM2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg'),
	(205, 'tt1475582', 'Sherlock', '2010–2017', '9.1', 'Crime, Drama, Mystery', 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.', 'Benedict Cumberbatch, Martin Freeman, Una Stubbs', 'https://www.imdb.com/title/tt1475582', 'https://m.media-amazon.com/images/M/MV5BMWY3NTljMjEtYzRiMi00NWM2LTkzNjItZTVmZjE0MTdjMjJhL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTQ4NTc5OTU@._V1_SX300.jpg'),
	(206, 'tt0988045', 'Sherlock Holmes', '2009', '7.6', 'Action, Adventure, Mystery', 'Detective Sherlock Holmes and his stalwart partner Watson engage in a battle of wits and brawn with a nemesis whose plot is a threat to all of England.', 'Robert Downey Jr., Jude Law, Rachel McAdams', 'https://www.imdb.com/title/tt0988045', 'https://m.media-amazon.com/images/M/MV5BMTg0NjEwNjUxM15BMl5BanBnXkFtZTcwMzk0MjQ5Mg@@._V1_SX300.jpg'),
	(207, 'tt2069840', 'M.O.G. Redux', '2012', '7.2', 'Short, Comedy, Drama', 'Friends discover the meaning of friendship with their new jobs.', 'Sean Durrie, Jed Reynolds, Chris Giuffria, Rudy Nunez', 'https://www.imdb.com/title/tt2069840', 'https://m.media-amazon.com/images/M/MV5BOWNmMzNmODAtMTI5Ny00MmY3LWFiNWEtM2RkNzcyMzQyM2Y1XkEyXkFqcGdeQXVyMTAxODMwNzM@._V1_SX300.jpg'),
	(208, 'tt1029340', 'Moebius Redux: A Life in Pictures', '2007', '7.3', 'Documentary', 'French artist and author Jean Giraud is one of the most famous and influential comic strip illustrators and authors of all time. He achieved his greatest fame as Moebius - not so much a ...', 'Enki Bilal, Philippe Druillet, H.R. Giger, Jean \'Moebius\' Giraud', 'https://www.imdb.com/title/tt1029340', 'https://m.media-amazon.com/images/M/MV5BY2FkMGNjODgtYjUwNy00MmEzLWEwZTEtYzEwYTZmYTkzM2Y0XkEyXkFqcGdeQXVyNjYyMzcwNjE@._V1_SX300.jpg'),
	(209, 'tt5779830', 'Starhunter ReduX', '2017–', '5.6', 'Action, Adventure, Sci-Fi', 'The story of the 44 episodes of Starhunter is revealed in \'Starhunter, Creator\'s Cut\' as originally intended by the show Creators. Censored scenes restored, bold ideas returned, episodes re-edited to match original scripts, never see', 'Tanya Allen, Michael Paré, Claudette Roche', 'https://www.imdb.com/title/tt5779830', 'https://m.media-amazon.com/images/M/MV5BMWRhZjYyMjQtMjQ2ZC00ZWM2LTgyYTMtZTBhYTBlNTYxZDlmXkEyXkFqcGdeQXVyMjAyOTg5Njg@._V1_SX300.jpg'),
	(210, 'tt0141560', 'Redux Riding Hood', '1997', '7.5', 'Animation, Short, Comedy', 'Years after failing to catch Little Red Riding Hood, the obsessed Wolf tries again.', 'Garrison Keillor, Michael Richards, Mia Farrow', 'https://www.imdb.com/title/tt0141560', 'https://m.media-amazon.com/images/M/MV5BMWRjZTFjZWUtMWQyZC00MmM3LTkzYWItNWE4MjIwOGVmNWRlXkEyXkFqcGdeQXVyMDM0MzU2NA@@._V1_SX300.jpg'),
	(211, 'tt11251590', 'Axeman: Redux', '2020', '3.8', 'Horror', 'Nine vacationing twenty-somethings are hunted by an ax-wielding local legend.', 'Elissa Dowling, Joston Theney, Tiffany Shepis', 'https://www.imdb.com/title/tt11251590', 'https://m.media-amazon.com/images/M/MV5BMDE4MzJiNDMtZDhhMy00YTA5LTg2MjAtZDI0YzE0ZDU2NDFhXkEyXkFqcGdeQXVyOTY4NDkwNw@@._V1_SX300.jpg'),
	(212, 'tt0395964', 'Chainsaw Redux: Making a Massacre', '2004', '6.4', 'Documentary', 'N/A', 'Jessica Biel, Jonathan Tucker, Erica Leerhsen, Mike Vogel', 'https://www.imdb.com/title/tt0395964', 'N/A'),
	(213, 'tt7532294', 'Unknown Redux', '2017', '7.0', 'Short, Sci-Fi, War', 'In an alternative Finnish War History, two Rogue Female Warriors try to transfer a Soviet Android to safety.', 'Pihla Viitala, Mimosa Willamo, Lauri Tilkanen, Timo Lavikainen', 'https://www.imdb.com/title/tt7532294', 'https://m.media-amazon.com/images/M/MV5BNzViZTc0MTAtYmQwNC00MWJlLTlkMzYtOThlOGVjNmI2YzBlXkEyXkFqcGdeQXVyODEwNDc2MDg@._V1_SX300.jpg'),
	(214, 'tt3350058', 'One Last Sunset Redux', '2015', '4.1', 'Action, Drama, Horror', 'A group of survivors struggle to exist as a virus begins to turn the entire human population into flesh eating zombies.', 'Clemeen Connolly, Addy Miller, Dahlia Legault', 'https://www.imdb.com/title/tt3350058', 'https://m.media-amazon.com/images/M/MV5BMTc0NTM3MjAyOV5BMl5BanBnXkFtZTgwODc3MTkwNjE@._V1_SX300.jpg'),
	(215, 'tt0774045', 'Pink Floyd The Wall Redux', '2002', '7.1', 'Drama, Music, War', 'A new interpretation of Pink Floyd\'s classic concept album updates the story from WWII to Vietnam, blending animation and archival footage with original images and live music. As rock star Pink flips channels in a hotel room, his min', 'Johanna Falls, John Hargrove, Michelle Hargrove', 'https://www.imdb.com/title/tt0774045', 'https://m.media-amazon.com/images/M/MV5BMTE5OTc1NDI4NV5BMl5BanBnXkFtZTcwMzI3MjczMQ@@._V1_SX300.jpg'),
	(216, 'tt1950119', 'Cyborg Clone Rambocop 12: This Time It\'s Personal the Revenge Redux Reloaded to the Limit', '2011', '8.6', 'Short, Comedy', 'Cyborg Clone Rambocop makes a promise to never fight again. America is taken over, his buddy the Colonel is captured, and his new girlfriend is kidnapped -the next day. It is up to Cyborg Clone Rambocop to fight for justice and Ameri', 'Max Aria, Dennis Kreusler, Karen Nicole', 'https://www.imdb.com/title/tt1950119', 'https://m.media-amazon.com/images/M/MV5BMjA2NDczMjU1Ml5BMl5BanBnXkFtZTcwODg5NTI1NQ@@._V1_SX300.jpg'),
	(217, 'tt0015324', 'Sherlock Jr.', '1924', '8.2', 'Action, Comedy, Romance', 'A film projectionist longs to be a detective, and puts his meagre skills to work when he is framed by a rival for stealing his girlfriend\'s father\'s pocketwatch.', 'Buster Keaton, Kathryn McGuire, Joe Keaton', 'https://www.imdb.com/title/tt0015324', 'https://m.media-amazon.com/images/M/MV5BZWFhOGU5NDctY2Q3YS00Y2VlLWI1NzEtZmIwY2ZiZjY4OTA2XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg'),
	(218, 'tt0086661', 'The Adventures of Sherlock Holmes', '1984–1985', '8.7', 'Crime, Drama, Mystery', 'Sherlock Holmes and Dr Watson solve the mysteries of copper beeches, a Greek interpreter, the Norwood builder, a resident patient, the red-headed league, and one final problem.', 'Jeremy Brett, David Burke, Rosalie Williams', 'https://www.imdb.com/title/tt0086661', 'https://m.media-amazon.com/images/M/MV5BOTU0ODg2ODMtZDQ0OS00N2MzLWIwYWUtZDQ2N2E2ZTZiNzI1XkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_SX300.jpg'),
	(219, 'tt0090357', 'Young Sherlock Holmes', '1985', '6.8', 'Adventure, Fantasy, Mystery', 'When assorted people start having inexplicable delusions that lead to their deaths, a teenage Sherlock Holmes decides to investigate.', 'Nicholas Rowe, Alan Cox, Sophie Ward', 'https://www.imdb.com/title/tt0090357', 'https://m.media-amazon.com/images/M/MV5BNmE0NTQ5ZjItN2MzNC00NjBhLTg0ZjYtYzFiMzFlMjhjNmNiXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg'),
	(220, 'tt2296777', 'Sherlock Gnomes', '2018', '5.2', 'Animation, Adventure, Comedy', 'Garden gnomes, Gnomeo (James McAvoy) and Juliet (Emily Blunt), recruit renowned detective Sherlock Gnomes (Johnny Depp) to investigate the mysterious disappearance of other garden ornaments.', 'Johnny Depp, James McAvoy, Emily Blunt', 'https://www.imdb.com/title/tt2296777', 'https://m.media-amazon.com/images/M/MV5BMTc2NjUzODMxMF5BMl5BanBnXkFtZTgwMzMwMDIzNDM@._V1_SX300.jpg'),
	(221, 'tt0066249', 'The Private Life of Sherlock Holmes', '1970', '7.1', 'Adventure, Comedy, Crime', 'When a bored Holmes eagerly takes the case of Gabrielle Valladon after an attempt on her life, the search for her missing husband leads to Loch Ness and the legendary monster.', 'Robert Stephens, Christopher Lee, Colin Blakely', 'https://www.imdb.com/title/tt0066249', 'https://m.media-amazon.com/images/M/MV5BNTg2ODQyOGQtNWVhMi00MDI2LTg3OTktZjA4MTJmYzQwYTFjXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg'),
	(222, 'tt0090509', 'The Return of Sherlock Holmes', '1986–1988', '8.7', 'Crime, Drama, Mystery', 'Sherlock Holmes and Dr Watson solve the mysteries of the devil\'s foot, Silver Blaze, Wisteria Lodge and the Bruce-Partington Plans.', 'Jeremy Brett, Edward Hardwicke, Rosalie Williams', 'https://www.imdb.com/title/tt0090509', 'https://m.media-amazon.com/images/M/MV5BMjM1OTc0MjMtZjFmOS00ZmQ0LTk1ZWItM2U1YTc5ODZjZjI3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg'),
	(223, 'tt0108855', 'The Memoirs of Sherlock Holmes', '1994', '8.6', 'Crime, Drama, Mystery', 'The last installment of Sherlock Holmes\' investigations.', 'Jeremy Brett, Rosalie Williams, Edward Hardwicke', 'https://www.imdb.com/title/tt0108855', 'https://m.media-amazon.com/images/M/MV5BMTYzMzEzMTM4Ml5BMl5BanBnXkFtZTcwMTY2NDYyMQ@@._V1_SX300.jpg'),
	(224, 'tt1515000', 'Episode #1.182', '2008', 'N/A', 'Comedy, News', 'Stories include: Rob Lowe suing three former employees. Simon Cowell discussing marriage. Kimberley Locke is asked out on a date by an American Idol contestant after a recent guest appearance.', 'Brian Mcdaniel, Simon Cowell, Jim Goldenberg, Dennis Hodges', 'https://www.imdb.com/title/tt1515000', 'N/A'),
	(225, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.imdb.com/title/', NULL),
	(226, 'tt0110357', 'The Lion King', '1994', '8.5', 'Animation, Adventure, Drama', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'Matthew Broderick, Jeremy Irons, James Earl Jones', 'https://www.imdb.com/title/tt0110357', 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg'),
	(227, 'tt6105098', 'The Lion King', '2019', '6.8', 'Animation, Adventure, Drama', 'After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.', 'Donald Glover, Beyoncé, Seth Rogen', 'https://www.imdb.com/title/tt6105098', 'https://m.media-amazon.com/images/M/MV5BMjIwMjE1Nzc4NV5BMl5BanBnXkFtZTgwNDg4OTA1NzM@._V1_SX300.jpg'),
	(228, 'tt0120131', 'The Lion King 2: Simba\'s Pride', '1998', '6.5', 'Animation, Adventure, Drama, Family, Musical, Romance', 'Simba\'s daughter is the key to a resolution of a bitter feud between Simba\'s pride and the outcast pride led by the mate of Scar.', 'Matthew Broderick, Neve Campbell, Andy Dick, Robert Guillaume', 'https://www.imdb.com/title/tt0120131', 'https://m.media-amazon.com/images/M/MV5BY2Y3MTk2MDgtOTc1Yy00ZmFjLThlNTEtMDQ1Y2EzZmRjMzVjXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg'),
	(229, 'tt0318403', 'The Lion King 3: Hakuna Matata', '2004', '6.5', 'Animation, Adventure, Comedy, Family, Musical', 'Timon the meerkat and Pumbaa the warthog retell the story of The Lion King (1994) from their own perspective.', 'Nathan Lane, Ernie Sabella, Julie Kavner, Jerry Stiller', 'https://www.imdb.com/title/tt0318403', 'https://m.media-amazon.com/images/M/MV5BOGZiMDQ1YTQtMGVlOC00OTJiLWFkYzMtYjdiYmY0NWM5YzVjXkEyXkFqcGdeQXVyOTg4MDk3MTQ@._V1_SX300.jpg'),
	(230, 'tt0323073', 'The Lion King', '1994', '8.0', 'Action, Adventure, Family', 'To survive and grow into a powerful adult lion, Simba must perfect his savage pounce and master fighting with all four paws. Scrap with hyenas, dash through an elephant graveyard, defeat your evil uncle Scar and recapture the Pridelands.', 'Jeremiah Hake, Robert Guillaume, Jeremy Irons, James Earl Jones', 'https://www.imdb.com/title/tt0323073', 'https://m.media-amazon.com/images/M/MV5BNzVmNzQ2ZmYtMmUzNy00MzhjLTg4ODUtMTQ0MjMzYTdkMDg5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg'),
	(231, 'tt2374051', 'Simba: The King Lion', '1995–', '6.8', 'Animation, Family', 'The Lion King is shot by poachers, as part of Shere Khan the Bengal tiger\'s plot to overthrow the king from his throne. Young Simba, son of the Lion King, suspects something strange and subconsciously senses that the Tiger will one d', 'N/A', 'https://www.imdb.com/title/tt2374051', 'https://m.media-amazon.com/images/M/MV5BNjkyOTczZGEtYmJhZC00ODIxLTg2NTQtNzUxNmNhZDgxN2Q1XkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg'),
	(232, 'tt0234092', 'Leo the Lion: King of the Jungle', '1994', '4.8', 'Animation, Adventure, Family', 'Leo the Lion, King of the Jungle, is estranged from his disaffected subjects. When he needs their help to rescue a young cub\'s mother from hunters, they refuse to give it unless he promises...', 'Tony Ail, Nathan Aswell, Bailee Reid, Kathleen Barr', 'https://www.imdb.com/title/tt0234092', 'https://m.media-amazon.com/images/M/MV5BOThjNzQ4MjktODE0Mi00NzM2LTljN2QtYjE5YWQ4NGQyOTNkXkEyXkFqcGdeQXVyODIxNjk4NzQ@._V1_SX300.jpg'),
	(233, 'tt0366742', 'The Making of \'The Lion King\'', '1994', '7.7', 'Documentary, Family', 'Behind the scenes look at the making of The Lion King.', 'Robert Guillaume, Jeffrey Katzenberg, Roy Edward Disney, Roger Allers', 'https://www.imdb.com/title/tt0366742', 'https://m.media-amazon.com/images/M/MV5BNmMxM2E3NWItZjUzOS00MmE4LTkyMmYtM2UwZTJhMDUyZTUwXkEyXkFqcGdeQXVyODA0MzEyNjU@._V1_SX300.jpg'),
	(234, 'tt0245234', 'The Lion King: A Musical Journey with Elton John', '1994', '7.8', 'Documentary, Music', 'The composers of the featured songs in the film, The Lion King, discuss and perform their creations for the film.', 'Elton John, Tim Rice, Roy Edward Disney, Jeffrey Katzenberg', 'https://www.imdb.com/title/tt0245234', 'N/A'),
	(235, 'tt0215934', 'The Lion King: Timon and Pumbaa\'s Jungle Games', '1995', '7.4', 'Action, Comedy, Family', 'Timon and Pumbaa, the funny side characters from Disney\'s The Lion King (1994), welcome you to their activity center. Play "bug drop", "burper", "jungle pinball", "sling shooter" or "hippo hop".', 'Ernie Sabella, Kevin Schon, Jim Piddock', 'https://www.imdb.com/title/tt0215934', 'https://m.media-amazon.com/images/M/MV5BZTY0NTZjMWItY2MxNS00MGFkLTk0MjMtMjQ4Y2QyNmFjNTk2XkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg');
/*!40000 ALTER TABLE `movies` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
